name = "ultima-thule"
license = "MIT"
licenselink = "https://github.com/alessiogiambrone/hugo-theme-ultima-thule/blob/master/LICENSE.md"
description = "A simple theme for Hugo based on hello-friend-ng."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Alessio Giambrone"
  homepage = "https://alessiogiambrone.github.io"

[original]
  name = "hello-friend-ng"
  homepage = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
